/**
 * Shared DTO, data-transformer objects, that Eden manages.
 *
 * The interfaces are loosely based on envelopes from tRPC.
 * @see https://github.com/trpc/trpc/blob/e543f3f3c86c9ad503a64d807ff4154ad6ec1637/packages/server/src/unstable-core-do-not-import/rpc/envelopes.ts
 */

import type { EdenRequestParams } from './config'
import type { JSONRPC2 } from './json-rpc'

export const procedures = ['query', 'mutation', 'subscription'] as const

/**
 * @public
 */
export type Procedure = (typeof procedures)[number]

/**
 * Request that the WebSocket client can send to terminate the subscription.
 *
 * @see https://github.com/trpc/trpc/blob/e543f3f3c86c9ad503a64d807ff4154ad6ec1637/packages/server/src/unstable-core-do-not-import/rpc/envelopes.ts#L94
 */
export interface EdenWsSubscriptionStopRequest extends JSONRPC2.Request {
  method: 'subscription.stop'
}

/**
 * Request that the WebSocket client can send to update connection params.
 *
 * @see https://github.com/trpc/trpc/blob/e543f3f3c86c9ad503a64d807ff4154ad6ec1637/packages/server/src/unstable-core-do-not-import/rpc/envelopes.ts#L94
 */
export interface EdenWsConnectionParamsRequest extends JSONRPC2.Request {
  method: 'connection-params'
  params: Dict<string> | null
}

/**
 * A fetch request that's sent over WebSockets.
 *
 * @see https://github.com/trpc/trpc/blob/f6efa479190996c22bc1e541fdb1ad6a9c06f5b1/packages/server/src/unstable-core-do-not-import/rpc/envelopes.ts#L87
 */
export interface EdenWsFetchRequest extends JSONRPC2.Request {
  method: Procedure

  params: {
    /**
     * The last event id that the client received
     */
    lastEventId?: string

    /**
     * EdenRequestParams for the request.
     */
    params?: EdenRequestParams
  }
}

export type EdenWsRequest =
  | (EdenWsSubscriptionStopRequest & { id: JSONRPC2.RequestId })
  | EdenWsConnectionParamsRequest
  | EdenWsFetchRequest

/**
 * This was originally a JSON-RPC 2.0 request object sent by the server.
 * @see https://github.com/trpc/trpc/blob/e543f3f3c86c9ad503a64d807ff4154ad6ec1637/packages/server/src/adapters/ws.ts#L566
 * @see https://www.jsonrpc.org/specification#request_object
 *
 * This will be converted to a result that is encapsulated by a JSON-RPC 2.0 response object.
 * It does not look like this result has any corresponding request.
 */
export interface EdenWsReconnectResult {
  type: 'reconnect'
  data?: never
  error?: never
}

/**
 * WebSocket client will emit this result once it has started.
 *
 * This is NOT emitted by the server, just generated by the client.
 */
export interface EdenWsStartedResult {
  type: 'started'
  data?: never
  error?: never
}

/**
 * WebSocket client will emit this result once it has stopped.
 *
 * This is NOT emitted by the server, just generated by the client.
 */
export interface EdenWsStoppedResult {
  type: 'stopped'
  data?: never
  error?: never
}

export interface EdenWsBaseState {
  type: 'state'
}

export interface EdenWsIdleState extends EdenWsBaseState {
  state: 'idle'
  data?: never
  error?: never
}

export interface EdenWsConnectingState<T> extends EdenWsBaseState {
  state: 'connecting'
  error?: T
  data?: never
}

export interface EdenWsPendingState extends EdenWsBaseState {
  state: 'pending'
  error?: never
  data?: never
}

export type EdenWsStateResult<T> = EdenWsIdleState | EdenWsConnectingState<T> | EdenWsPendingState

/**
 * Based on the official eden treaty response.
 * @see https://github.com/elysiajs/eden/blob/7b4e3d90f9f69bc79ca108da4f514ee845c7d9d2/src/treaty2/types.ts#L194-L218
 *
 * The status and headers properties have been omitted because they seem redundant.
 */
export interface EdenFetchBaseResult {
  response: Response
}

/**
 * Based on the official eden success response result.
 * @see https://github.com/elysiajs/eden/blob/7b4e3d90f9f69bc79ca108da4f514ee845c7d9d2/src/treaty2/types.ts#L196-L200
 */
export interface EdenFetchSuccessResult<T> extends EdenFetchBaseResult {
  /**
   * The id of the message to keep track of in case of a reconnect
   */
  id?: string

  /**
   * Constant type to discriminate between results.
   */
  type?: 'data'

  /**
   * The data will be defined for a successful response.
   */
  data: T

  /**
   * There will be no error for a successful response.
   */
  error?: null
}

/**
 * Based on the official eden error response result.
 * @see https://github.com/elysiajs/eden/blob/7b4e3d90f9f69bc79ca108da4f514ee845c7d9d2/src/treaty2/types.ts#L203-L217
 */
export interface EdenFetchErrorResult<T> extends EdenFetchBaseResult {
  /**
   * The id of the message to keep track of in case of a reconnect
   */
  id?: string

  /**
   * This property is added for type discrimination, and it is omitted in the actual result.
   */
  type?: never

  /**
   * There will be no top-level data for an error response.
   * However, {@link T} should be a custom error class that may contain additional information.
   *
   * In the case of the official library, the error will contain "value" and "status", which
   * contain the the response data and response status respectively.
   *
   * @see https://github.com/elysiajs/eden/blob/7b4e3d90f9f69bc79ca108da4f514ee845c7d9d2/src/treaty2/types.ts#L204-L214
   */
  data?: null

  /**
   * The error for an error response. It should be a custom error class that contains
   * additional information about the error, such as the response data and status.
   */
  error: T
}

export type EdenErrorResult<T> = EdenFetchErrorResult<T>

/**
 * Primarily intended for usage by the WebSocket client.
 * A union of all possible results, i.e. unwrapped in a JSON-RPC-esque object.
 */
export type EdenSuccessResult<T> =
  | EdenFetchSuccessResult<T>
  | EdenWsStartedResult
  | EdenWsStoppedResult
  | EdenWsReconnectResult

/**
 * Any valid result.
 */
export type EdenResult<TData = any, TError = any> =
  | EdenSuccessResult<TData>
  | EdenErrorResult<TError>
  | EdenWsStateResult<TError>

/**
 * For convenience, both error and result are defined in the interface for discrimination capabilities.
 * Based on the JSON-RPC 2.0 specification, the presence of either is mutually exclusive.
 *
 * @see https://github.com/trpc/trpc/blob/e543f3f3c86c9ad503a64d807ff4154ad6ec1637/packages/server/src/unstable-core-do-not-import/rpc/envelopes.ts#L73
 * @see https://www.jsonrpc.org/specification#response_object
 */
export interface EdenSuccessResponse<T> extends JSONRPC2.SuccessResponse {
  result: EdenSuccessResult<T>
  error?: never
}

/**
 * For convenience, both error and result are defined in the interface for discrimination capabilities.
 * Based on the JSON-RPC 2.0 specification, the presence of either is mutually exclusive.
 *
 * @see https://www.jsonrpc.org/specification#response_object
 */
export interface EdenErrorResponse<T> extends JSONRPC2.ErrorResponse {
  result?: never
  error: EdenErrorResult<T>
}

/**
 * A union of all possible responses.
 */
export type EdenResponse<TData = unknown, TError = unknown> =
  | EdenSuccessResponse<TData>
  | EdenErrorResponse<TError>

/**
 * Basically like {@link EdenResponse} but with a defined ID.
 */
export type EdenWsIncomingMessage<TData = unknown, TError = unknown> = {
  id: JSONRPC2.RequestId
} & EdenResponse<TData, TError>

/**
 * Basically like {@link EdenWsRequest} but with a defined ID.
 */
export type EdenWsOutgoingMessage = {
  id: JSONRPC2.RequestId
} & EdenWsRequest
