import type { InvertKeyValue, ValueOf } from '../utils/types'

/**
 * Error codes that may be generated by the server while handling a response.
 */
export const EDEN_INTERNAL_SERVER_ERROR_CODES = {
  INTERNAL_SERVER_ERROR: -32603, // 500
  NOT_IMPLEMENTED: -32603, // 501
  BAD_GATEWAY: -32603, // 502
  SERVICE_UNAVAILABLE: -32603, // 503
  GATEWAY_TIMEOUT: -32603, // 504
} as const

/**
 * Error codes that may be generated by the server while handling a response.
 */
export const EDEN_SERVER_ERROR_CODES = {
  ...EDEN_INTERNAL_SERVER_ERROR_CODES,
} as const

/**
 * Error codes that may be generated by the client while resolving a request.
 */
export const EDEN_CLIENT_FETCH_ERROR_CODES = {} as const

/**
 * Error codes that may be generated by a WebSocket client.
 */
export const EDEN_CLIENT_WEB_SOCKET_ERROR_CODES = {
  WEBSOCKET_CLOSED: -32500,
  WEBSOCKET_TIMEOUT: -32501,
  WEBSOCKET_INITIALIZATION_FAILED: -32502,
  WEBSOCKET_RECONNECT: -32503,
} as const

/**
 * Error codes that may be generated by the client.
 */
export const EDEN_CLIENT_ERROR_CODES = {
  ...EDEN_CLIENT_FETCH_ERROR_CODES,
  ...EDEN_CLIENT_WEB_SOCKET_ERROR_CODES,
} as const

/**
 * All error codes enumerated by their key.
 *
 * @see https://github.com/trpc/trpc/blob/f159ab9c4fa2b428a8d1bd0d69232976032f7996/packages/server/src/unstable-core-do-not-import/rpc/codes.ts#L11
 */
export const EDEN_ERROR_CODES = {
  ...EDEN_SERVER_ERROR_CODES,
  ...EDEN_CLIENT_ERROR_CODES,
} as const

/**
 * All error codes enumerated by their numeric code.
 *
 * @see https://github.com/trpc/trpc/blob/f159ab9c4fa2b428a8d1bd0d69232976032f7996/packages/server/src/unstable-core-do-not-import/rpc/codes.ts#L45
 */
export const EDEN_ERROR_CODES_BY_NUMBER: InvertKeyValue<typeof EDEN_ERROR_CODES> = {
  [-32603]: 'INTERNAL_SERVER_ERROR',
  [-32500]: 'WEBSOCKET_CLOSED',
  [-32501]: 'WEBSOCKET_TIMEOUT',
  [-32502]: 'WEBSOCKET_INITIALIZATION_FAILED',
  [-32503]: 'WEBSOCKET_RECONNECT',
}

export type EDEN_ERROR_CODE_NUMBER = ValueOf<typeof EDEN_ERROR_CODES>

export type EDEN_ERROR_CODE = keyof typeof EDEN_ERROR_CODES

export type EDEN_CLIENT_ERROR_CODE_NUMBER = ValueOf<typeof EDEN_CLIENT_ERROR_CODES>

export type EDEN_CLIENT_ERROR_CODE = keyof typeof EDEN_CLIENT_ERROR_CODES

export type EDEN_SERVER_ERROR_CODE_NUMBER = ValueOf<typeof EDEN_SERVER_ERROR_CODES>

export type EDEN_SERVER_ERROR_CODE = keyof typeof EDEN_SERVER_ERROR_CODES
